name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.kanzparty.com.br
        username: kanzparty
        password: HFt2pR7kB5
        local-dir: ./ 
        server-dir: ../apps_nodejs/api/
